### PR TITLE
bug fix: updated the version of tiny-skia

### PR DESCRIPTION
**Pull request by kunzaatko**
When updated the version of tiny-skia package to the current master
(0.4.2) the problem is fixed. It was in having multiple `tiny-skia`
packages. (0.4.2)  as a dependency and (0.3.0) from the `Cargo.toml`.

[Ticket: #6]

### CODE REVIEW

**Comment by carrascomj** [comment]
Thank you for the update!

For some reason, resvg is being pulled with version 0.13.1 in fresh installs, even though it is pinned to 0.13.0. I'll update that one too and will upload the Cargo.lock since it makes sense in a binary crate like dalted.

**Comment by kunzaatko** [comment]
I think that the update of `resvg` is intentional by `cargo`. It should be a non-breaking change by the semantic versioning, so it updated automatically. I looked it up right now, so you can check, whether I understand the  [SemVer  rust resolver](https://doc.rust-lang.org/cargo/reference/resolver.html).

**Comment by kunzaatko** [comment]
After further reading: If there is a reason to pin the patch version (the third number), should do this:
```toml
resvg = "=0.13.0"
```
notice the `"=..."`. There should not be a reason to do that though.

**Comment by kunzaatko** [comment]
After further reading: If there is a reason to pin the patch version (the third number), should do this:
```toml
resvg = "=0.13.0"
```
notice the `"=..."`. There should not be a reason to do that though.

**Comment by carrascomj** [comment]
@kunzaatko Oh, my fault, then. I thought I was pinning them just by writing the full version, I didn't know that rust resolves deps with semantic versioning (which is fantastic, actually). Thanks for the pointers!

**Pull request merged**
